"""
dialogue discourse relations ditc
"""
relations_vocab = {
    "global": 0,
    "Comment": 1,
    "Clarification_question": 2,
    "Elaboration": 3,
    "Acknowledgement": 4,
    "Continuation": 5,
    "Explanation": 6,
    "Conditional": 7,
    "Question-answer_pair": 8,
    "Alternation": 9,
    "Q-Elab": 10,
    "Result": 11,
    "Background": 12,
    "Narration": 13,
    "Correction": 14,
    "Parallel": 15,
    "Contrast": 16,
    "Comment_INV": 17,
    "Clarification_question_INV": 18,
    "Elaboration_INV": 19,
    "Acknowledgement_INV": 20,
    "Continuation_INV": 21,
    "Explanation_INV": 22,
    "Conditional_INV": 23,
    "Question-answer_pair_INV": 24,
    "Alternation_INV": 25,
    "Q-Elab_INV": 26,
    "Result_INV": 27,
    "Background_INV": 28,
    "Narration_INV": 29,
    "Correction_INV": 30,
    "Parallel_INV": 31,
    "Contrast_INV": 32,
}
